# Site wide configuration

title: CahulPan
description: "Cahulpan"
logo: 120x120.gif
teaser: 400x250.gif
locale: en_US
url: http://mbit.ws/cahulpan/

# Jekyll configuration

sass:
  sass_dir: _sass
  style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: rogue
gems:
  - jekyll-sitemap


# Site owner
owner:
  name: MBIt
  web: http://mbit.ws
  email: lxmbit@gmail.com
  twitter: 
  bio: "Just another boring, tattooed, time traveling designer."
  avatar: bio-photo.jpg # 160x160 px image for author byline
  google:
    plus: 
    ad-client: 
    ad-slot: 
  disqus-shortname:


exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]